'Mapnik python bindings'
from pathlib import Path

from setuptools import setup, Extension
import os


excludes = [
    'vendor/mapnik/src/json/extract_bounding_boxes_x3.cpp',
    'vendor/mapnik/src/json/feature_from_geojson.cpp',
    'vendor/mapnik/src/json/feature_grammar_x3.cpp',
    'vendor/mapnik/src/json/generic_json_grammar_x3.cpp',
    'vendor/mapnik/src/json/geojson_grammar_x3.cpp',
    'vendor/mapnik/src/json/geometry_from_geojson.cpp',
    'vendor/mapnik/src/json/mapnik_feature_to_geojson.cpp',
    'vendor/mapnik/src/json/mapnik_geometry_to_geojson.cpp',
    'vendor/mapnik/src/json/mapnik_json_generator_grammar.cpp',
    'vendor/mapnik/src/json/parse_feature.cpp',
    'vendor/mapnik/src/json/positions_grammar_x3.cpp',
    'vendor/mapnik/src/json/topojson_grammar_x3.cpp',
    'vendor/mapnik/src/json/unicode_string_grammar_x3.cpp',
    'vendor/mapnik/src/libxml2_loader.cpp',
    'vendor/mapnik/src/rapidxml_loader.cpps',
    'vendor/mapnik/src/svg/output/process_line_symbolizer.cpp',
    'vendor/mapnik/src/svg/output/process_polygon_symbolizer.cpp',
    'vendor/mapnik/src/svg/output/process_symbolizers.cpp',
    'vendor/mapnik/src/svg/output/svg_generator.cpp',
    'vendor/mapnik/src/svg/output/svg_output_attributes.cpp',
    'vendor/mapnik/src/svg/output/svg_output_grammars.cpp',
    'vendor/mapnik/src/svg/output/svg_renderer.cpp',
    'vendor/mapnik/src/util/utf_conv_win.cpp',
    'vendor/mapnik/src/wkt/geometry_to_wkt.cpp',
    'vendor/mapnik/src/wkt/mapnik_wkt_generator_grammar.cpp',
    'vendor/mapnik/src/wkt/wkt_factory.cpp',
    'vendor/mapnik/src/wkt/wkt_grammar_x3.cpp',
]
src = [str(p) for p in Path('vendor/mapnik/src').glob('**/*.cpp')
       if str(p) not in excludes]
src += [str(p) for p in Path('vendor/mapnik/deps/agg/src').glob('*.cpp')]

os.environ["CC"] = 'ccache clang++'

# from python-config --cflags
cflags = [
    '-c',
    '-I/home/ybon/.virtualenvs/mapnikio/include/python3.6m',
    '-Wno-unused-result',
    '-Wsign-compare',
    '-DNDEBUG',
    '-fwrapv',
    '-O3',
    '-Wall',
    '-Wstrict-prototypes',
    '-march=x86-64',
    '-mtune=generic',
    '-O2',
    '-pipe',
    '-fstack-protector-strong',
    '-march=x86-64',
    '-mtune=generic',
    '-O2',
    '-pipe',
    '-fstack-protector-strong',
    '-march=x86-64',
    '-mtune=generic',
    '-O2',
    '-pipe',
    '-fstack-protector-strong',
    '-I/usr/include/cairo',
    '-I/usr/include/pixman-1',
    '-I/usr/include/libdrm',
    '-Ivendor/mapnik/deps/',
    '-Ivendor/mapnik/deps/mapbox/variant/include/',
    '-Ivendor/mapnik/deps/mapbox/geometry/include/',
    '-Ivendor/mapnik/deps/mapbox/protozero/include/',
    '-Ivendor/mapnik/deps/agg/include/',
    '-Ivendor/mapnik/include/',
    '-I/usr/include',
    '-I/usr/include/freetype2',
    '-I/usr/include/libpng16',
    '-I/usr/include/harfbuzz',
    '-I/usr/include/glib-2.0',
    '-I/usr/lib/glib-2.0/include',
    '-DMAPNIK_MEMORY_MAPPED_FILE',
    '-DMAPNIK_HAS_DLCFN',
    '-DBIGINT',
    '-DBOOST_REGEX_HAS_ICU',
    '-DHAVE_JPEG',
    '-DMAPNIK_USE_PROJ4',
    '-DHAVE_PNG',
    '-DHAVE_TIFF',
    '-DHAVE_WEBP',
    '-DLINUX',
    '-DMAPNIK_THREADSAFE',
    '-DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1',
    '-DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1',
    '-DBOOST_SPIRIT_USE_PHOENIX_V3=1',
    '-DNDEBUG',
    '-DHAVE_CAIRO',
    '-DGRID_RENDERER',
    '-std=c++14',
    '-ftemplate-depth-300',
    '-Wshadow',
    '-O3',
]

ldflags = [
    '-L/usr/lib',
    '-lpython3.6m',
    '-L/usr/lib',
    '-lpthread',
    '-lboost_filesystem',
    '-lboost_regex',
    '-lcairo',
    '-lpng',
    '-lproj',
    '-ltiff',
    '-lxml2',
    '-licui18n',
    '-lboost_system',
    '-lharfbuzz',
    '-ljpeg',
    '-lwebp',
    '-licuuc',
    '-lfreetype',
    '-lz',
    '-ldl',
    '-lboost_python3',
    '-lboost_thread',
    '-lboost_system',
    '-lrt',
    '-Wl,-z,origin',
    '-Wl,-rpath=$ORIGIN/lib',
]


setup(
    name='mapnikio',
    version='0.0.1',
    description=__doc__,
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3',
        'Operating System :: POSIX',
        'Operating System :: MacOS :: MacOS X',
        'Environment :: Web Environment',
        'Development Status :: 4 - Beta',
    ],
    platforms=['POSIX'],
    author='Yohan Boniface',
    author_email='yohan.boniface@data.gouv.fr',
    license='MIT',
    packages=['mapnikio'],
    ext_modules=[Extension(
        "mapnikio.map",
        sources=["mapnikio/map.cpp"] + src,
        extra_compile_args=cflags,
        extra_link_args=ldflags,
        language="c++",
    )],
    provides=['mapnikio'],
    include_package_data=True,
)
